FROM nginx

LABEL version="1.0.0" description="Container Nginx and NodeJS" maintainer="Thiago Cruz<thagocruz@gmail.com>"

WORKDIR /app

COPY ./start.dev.sh /start.sh
COPY ./app /app

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash
RUN apt-get install -y nodejs
RUN npm install -g nodemon

COPY ./default.conf /etc/nginx/conf.d/default.conf

VOLUME /app

ENV PORT=3000

EXPOSE 80

CMD ["/start.sh"]